lit_module:
  name: conv2_net
  path: configs/modules/conv_net.yml

  optimizer:
    lr: 0.001

  scheduler:
    factor: 0.5
    patience: 15
    min_lr: 0.00001

trainer:
  accelerator: gpu
  devices: [0, 1, 2, 3]
  max_epochs: -1

  logger:
    path: /scratch/algo/shpakovych/tsp/logs

  checkpointer:
    path: /scratch/algo/shpakovych/tsp/checkpoints
    save_top_k: 5
    verbose: True
    monitor: val_loss
    mode: min
    save_last: True

  progress_bar:
    refresh_rate: 1

loaders:
  seed: 42
  test_size: 0.05
  batch_size: 16
  num_workers: 4
  num_sanity_val_steps: 1
  check_val_every_n_epoch: 1